import 'package:flutter/material.dart';
import '../../../widgets/experience_ui.dart';

class LgsMathJourney {
  const LgsMathJourney({
    required this.id,
    required this.topicName,
    required this.heroName,
    required this.tagline,
    required this.masteryGoal,
    required this.commonTrap,
    required this.warmUpQuestion,
    required this.bossQuestion,
    required this.skillChips,
    required this.quickPrompts,
    required this.icon,
    required this.accent,
    required this.xpReward,
    required this.difficulty,
  });

  final String id;
  final String topicName;
  final String heroName;
  final String tagline;
  final String masteryGoal;
  final String commonTrap;
  final String warmUpQuestion;
  final String bossQuestion;
  final List<String> skillChips;
  final List<String> quickPrompts;
  final IconData icon;
  final Color accent;
  final int xpReward;
  final int difficulty;
}

class LgsMathLearningCatalog {
  const LgsMathLearningCatalog._();

  static const List<LgsMathJourney> journeys = <LgsMathJourney>[
    LgsMathJourney(
      id: 'lgs_carpanlar',
      topicName: 'Carpanlar ve Katlar',
      heroName: 'Sayi Dedektifi',
      tagline: 'Sayilarin gizli baglarini kesfet.',
      masteryGoal: 'EBOB-EKOK problemlerini sezgiyle coz.',
      commonTrap: 'EBOB ile EKOK karistirmak.',
      warmUpQuestion: '12 ve 18 in ortak carpanlarini bul.',
      bossQuestion: 'Uc sayinin EKOK unu bulmak icin en kisa yolu kesfet.',
      skillChips: <String>['Asal carpan', 'EBOB', 'EKOK'],
      quickPrompts: <String>['Carpanlar ve katlar farkini anlat.', 'EBOB ve EKOK ornegi coz.', 'Mini test ver.'],
      icon: Icons.search_rounded,
      accent: AppColors.subjectMat,
      xpReward: 80,
      difficulty: 1,
    ),
    LgsMathJourney(
      id: 'lgs_uslu',
      topicName: 'Uslu Ifadeler',
      heroName: 'Us Ustasi',
      tagline: 'Kucuk sayilarla buyuk sonuclar uret.',
      masteryGoal: 'Us kurallarini formul ezberlemeden uygula.',
      commonTrap: 'Negatif tabanda isaret hatasi yapmak.',
      warmUpQuestion: '2 uzeri 3 carpi 2 uzeri 4 kac eder?',
      bossQuestion: 'Farkli tabanli us ifadelerini karsilastir.',
      skillChips: <String>['Carpma kurali', 'Bolme kurali', 'Sifir us'],
      quickPrompts: <String>['Uslu ifade kurallarini anlat.', 'Negatif taban ornegi coz.', 'Us karsilastirma sorusu ver.'],
      icon: Icons.bolt_rounded,
      accent: AppColors.subjectFizik,
      xpReward: 80,
      difficulty: 2,
    ),
    LgsMathJourney(
      id: 'lgs_karekok',
      topicName: 'Karekoklu Ifadeler',
      heroName: 'Kok Gezgini',
      tagline: 'Koklerin icindeki duzeni gor.',
      masteryGoal: 'Karekok sadelestrmeyi refleks haline getir.',
      commonTrap: 'Kok icindeki toplami ayri ayri kok almak.',
      warmUpQuestion: 'Karekok 48 i sadelestir.',
      bossQuestion: 'Iki karekoklu ifadeyi karsilastir.',
      skillChips: <String>['Sadelestrme', 'Carpma', 'Bolme'],
      quickPrompts: <String>['Karekok sadelestrmeyi anlat.', 'Karekoklu ifade ornegi coz.', 'Mini test ver.'],
      icon: Icons.square_foot_rounded,
      accent: AppColors.teal,
      xpReward: 90,
      difficulty: 2,
    ),
    LgsMathJourney(
      id: 'lgs_veri',
      topicName: 'Veri Analizi',
      heroName: 'Veri Avcisi',
      tagline: 'Tablolardan hikaye cikar.',
      masteryGoal: 'Grafik ve tabloyu hizli okuyup yorum yap.',
      commonTrap: 'Ortalama ile medyani karistirmak.',
      warmUpQuestion: '5, 7, 3, 9, 6 sayilarinin ortalamasini bul.',
      bossQuestion: 'Bir veri setinden tum yorumlari listele.',
      skillChips: <String>['Ortalama', 'Medyan', 'Mod'],
      quickPrompts: <String>['Ortalama medyan mod farkini anlat.', 'Grafik okuma ornegi coz.', 'Mini test ver.'],
      icon: Icons.bar_chart_rounded,
      accent: AppColors.accent,
      xpReward: 70,
      difficulty: 1,
    ),
    LgsMathJourney(
      id: 'lgs_olasilik',
      topicName: 'Basit Olaylarin Olma Olasiligi',
      heroName: 'Sans Muhendisi',
      tagline: 'Olasiligi tahmin degil hesap yap.',
      masteryGoal: 'Olasilik kesrini dogru kur.',
      commonTrap: 'Toplam olay sayisini yanlis saymak.',
      warmUpQuestion: 'Bir zarla 3 ten buyuk sayi gelme olasiligi nedir?',
      bossQuestion: 'Iki olayin birlikte gerceklesme olasiligini hesapla.',
      skillChips: <String>['Kesir', 'Olay sayisi', 'Yorum'],
      quickPrompts: <String>['Olasilik nedir kisa anlat.', 'Zar olasilik ornegi coz.', 'Mini test ver.'],
      icon: Icons.casino_rounded,
      accent: AppColors.warning,
      xpReward: 70,
      difficulty: 1,
    ),
    LgsMathJourney(
      id: 'lgs_cebir',
      topicName: 'Cebirsel Ifadeler ve Ozdeslikler',
      heroName: 'Cebir Mimari',
      tagline: 'Harflerle dusunmeyi ogren.',
      masteryGoal: 'Ozdeslik kaliplarini gorerek uygula.',
      commonTrap: 'Isaret dagiliminda hata yapmak.',
      warmUpQuestion: '(x+3)(x-3) ifadesini ac.',
      bossQuestion: 'Bir ozdeslik sorusunu ters yonden coz.',
      skillChips: <String>['Ozdeslik', 'Acilim', 'Carpanlara ayirma'],
      quickPrompts: <String>['Ozdeslik nedir anlat.', 'Carpanlara ayirma ornegi coz.', 'Mini test ver.'],
      icon: Icons.functions_rounded,
      accent: AppColors.subjectMat,
      xpReward: 90,
      difficulty: 2,
    ),
    LgsMathJourney(
      id: 'lgs_denklem',
      topicName: 'Dogrusal Denklemler',
      heroName: 'Denklem Cozucusu',
      tagline: 'Bilinmeyeni bulmak bulmaca cozmek gibi.',
      masteryGoal: 'Denklem kurma ve cozmeyi refleks yap.',
      commonTrap: 'Esitligin iki tarafina ayni islemi unutmak.',
      warmUpQuestion: '2x + 5 = 11 denklemini coz.',
      bossQuestion: 'Sozel problemden denklem kur ve coz.',
      skillChips: <String>['Kurma', 'Cozme', 'Yorum'],
      quickPrompts: <String>['Denklem cozum adimlarini anlat.', 'Sozel problemden denklem kur.', 'Mini test ver.'],
      icon: Icons.calculate_rounded,
      accent: AppColors.subjectFizik,
      xpReward: 85,
      difficulty: 2,
    ),
    LgsMathJourney(
      id: 'lgs_esitsizlik',
      topicName: 'Esitsizlikler',
      heroName: 'Sinir Avcisi',
      tagline: 'Buyuk mu kucuk mu siniri bul.',
      masteryGoal: 'Esitsizliklerde yon degisimini iceselletir.',
      commonTrap: 'Negatif sayiyla carpinca yonu degistirmeyi unutmak.',
      warmUpQuestion: '-2x > 6 esitsizligini coz.',
      bossQuestion: 'Iki esitsizligi ayni anda saglayan araligi bul.',
      skillChips: <String>['Yon', 'Aralik', 'Sayi dogrusu'],
      quickPrompts: <String>['Esitsizlik nedir anlat.', 'Negatif carpma ornegi coz.', 'Mini test ver.'],
      icon: Icons.compare_arrows_rounded,
      accent: AppColors.teal,
      xpReward: 80,
      difficulty: 2,
    ),
    LgsMathJourney(
      id: 'lgs_ucgen',
      topicName: 'Ucgenler',
      heroName: 'Ucgen Kasifi',
      tagline: 'Uc kenar sonsuz sir.',
      masteryGoal: 'Ucgen esitsizligini ve aci hesabini otomatiklestir.',
      commonTrap: 'Dis aci ile ic aciyi karistirmak.',
      warmUpQuestion: 'Ic acilari 50 60 ve x olan ucgende x i bul.',
      bossQuestion: 'Dis acilerle ic aciler arasindaki iliskiyi kesfet.',
      skillChips: <String>['Aci', 'Kenar', 'Esitsizlik'],
      quickPrompts: <String>['Ucgen cesitlerini anlat.', 'Aci hesabi ornegi coz.', 'Mini test ver.'],
      icon: Icons.change_history_rounded,
      accent: AppColors.accent,
      xpReward: 90,
      difficulty: 3,
    ),
    LgsMathJourney(
      id: 'lgs_eslik',
      topicName: 'Eslik ve Benzerlik',
      heroName: 'Ayni mi Benzer mi',
      tagline: 'Sekillerin gizli akrabaliklarini bul.',
      masteryGoal: 'Eslik ve benzerlik sartlarini ayirt et.',
      commonTrap: 'Benzerlikte oran yerine fark kullanmak.',
      warmUpQuestion: 'Iki ucgenin esit olma sartlarini say.',
      bossQuestion: 'Benzer ucgenlerde bilinmeyen kenari oran ile bul.',
      skillChips: <String>['Eslik', 'Benzerlik', 'Oran'],
      quickPrompts: <String>['Eslik benzerlik farkini anlat.', 'Benzerlik orani ornegi coz.', 'Mini test ver.'],
      icon: Icons.content_copy_rounded,
      accent: AppColors.warning,
      xpReward: 85,
      difficulty: 3,
    ),
    LgsMathJourney(
      id: 'lgs_donusum',
      topicName: 'Donusum Geometrisi',
      heroName: 'Sekil Sihirbazi',
      tagline: 'Kaydir dondur yansit.',
      masteryGoal: 'Donusum turleri arasinda gecis yap.',
      commonTrap: 'Yansima eksenini yanlis belirlemek.',
      warmUpQuestion: 'Bir noktanin x eksenine gore yansismasini bul.',
      bossQuestion: 'Art arda iki donusum uygula ve sonucu yor.',
      skillChips: <String>['Yansima', 'Donme', 'Oteleme'],
      quickPrompts: <String>['Donusum cesitlerini anlat.', 'Yansima ornegi coz.', 'Mini test ver.'],
      icon: Icons.flip_rounded,
      accent: AppColors.subjectMat,
      xpReward: 80,
      difficulty: 2,
    ),
    LgsMathJourney(
      id: 'lgs_cisim',
      topicName: 'Geometrik Cisimler',
      heroName: 'Boyut Atlayici',
      tagline: '2D den 3D ye gecis yap.',
      masteryGoal: 'Hacim ve alan formullerini anlamli kullan.',
      commonTrap: 'Yaricap ile capi karistirmak.',
      warmUpQuestion: 'Kenari 5 cm olan kupun hacmini bul.',
      bossQuestion: 'Bir silindirin icine yerlesen en buyuk kupu bul.',
      skillChips: <String>['Hacim', 'Alan', 'Acilim'],
      quickPrompts: <String>['Temel cisimlerin hacim formullerini anlat.', 'Silindir hacmi ornegi coz.', 'Mini test ver.'],
      icon: Icons.view_in_ar_rounded,
      accent: AppColors.subjectFizik,
      xpReward: 90,
      difficulty: 3,
    ),
  ];
}
